USE [master]
GO

/****** Object:  Database [FamilyTreeDb]    Script Date: 8/29/2019 9:41:54 AM ******/
DROP DATABASE [FamilyTreeDb]
GO

/****** Object:  Database [FamilyTreeDb]    Script Date: 8/29/2019 9:41:54 AM ******/
CREATE DATABASE [FamilyTreeDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FamilyTreeDb', FILENAME = N'C:\Users\sadki\FamilyTreeDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FamilyTreeDb_log', FILENAME = N'C:\Users\sadki\FamilyTreeDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FamilyTreeDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FamilyTreeDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FamilyTreeDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FamilyTreeDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FamilyTreeDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FamilyTreeDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FamilyTreeDb] SET  MULTI_USER 
GO

ALTER DATABASE [FamilyTreeDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FamilyTreeDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FamilyTreeDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FamilyTreeDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FamilyTreeDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FamilyTreeDb] SET QUERY_STORE = OFF
GO

USE [FamilyTreeDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [FamilyTreeDb] SET  READ_WRITE 
GO


